version: "3"
services:
  es01:
    container_name: es01
    hostname: es01
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}"
    environment:
      - node.name=es01
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=node02
      - cluster.initial_master_nodes=node01,node02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms724m -Xmx724m"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      - es-network

  es02:
    container_name: es02
    hostname: es02
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}"
    environment:
      - node.name=es02
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms724m -Xmx724m"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data02:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - es-network

  kibana:
    container_name: kibana
    hostname: kibana
    image: "docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}"
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - "ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}"
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml  
    networks:
      - es-network
    depends_on:
      - es01
      - es02

  heartbeat:
    container_name: heartbeat
    hostname: heartbeat
    image: "docker.elastic.co/beats/heartbeat:${ELASTIC_VERSION}"
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    depends_on:
      - es01
      - es02
    environment:
      - "ES_PASSWORD=${ELASTIC_PASSWORD}"
    command: heartbeat -e -strict.perms=false
    networks: 
      - es-network
    restart: on-failure
  
  logstash:
    container_name: logstash
    hostname: logstash
    image: "docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - es-network
    depends_on:
      - es01
      - es02
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    restart: on-failure

volumes:
  es-data01:
    driver: local
  es-data02:
    driver: local

networks:
  es-network:
    driver: bridge
