version: "3"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=node02
      - cluster.initial_master_nodes=node01,node02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms724m -Xmx724m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-network

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-cluster-7
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms724m -Xmx724m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data02:/usr/share/elasticsearch/data
    networks:
      - es-network

volumes:
  es-data01:
    driver: local
  es-data02:
    driver: local

networks:
  es-network:
    driver: bridge