version: '3.8'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/postgresql.docker.conf:/etc/postgresql/postgresql.conf
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres/data/:/var/lib/postgresql/data:rw
      - pg-log-data:/var/log/postgresql/:rw
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf -c listen_addresses='*'
    networks:
      - psql-network
    ports:
      - "5432:5432"

  psql-metricbeat:
    container_name: psql-metricbeat
    hostname: psql-metricbeat
    image: "docker.elastic.co/beats/metricbeat:${ELASTIC_VERSION}"
    user: root
    command:
      - -e
      - --strict.perms=false
      - --system.hostfs=/hostfs
    environment:
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "ELASTIC_HOSTS=${ELASTIC_HOSTS}"
      - "KIBANA_HOST=${KIBANA_HOST}"
      - "POSTGRES_HOST=${POSTGRES_HOST}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    volumes:
      - type: bind
        source: ./metricbeat/config/metricbeat.yml
        target: /usr/share/metricbeat/metricbeat.yml
        read_only: true
      - type: bind
        source: /
        target: /hostfs
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - psql-network
    depends_on:
      - postgres

  psql-filebeat:
    container_name: psql-filebeat
    hostname: psql-filebeat
    image: "docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}"
    user: root
    command:
      - -e
      - --strict.perms=false
    environment:
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "ELASTIC_HOSTS=${ELASTIC_HOSTS}"
      - "KIBANA_HOST=${KIBANA_HOST}"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - pg-log-data:/var/log/postgresql/:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - psql-network
    depends_on:
      - postgres
      
volumes:
  pg-log-data:
    driver: local

networks:
  psql-network:
    driver: bridge
