version: '3.8'
services:
  prom-prometheus:
    image: prom/prometheus
    container_name: prom-prometheus
    hostname: prom-prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prom-network
    ports:
      - "9090:9090"
      - "996:996"

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  prom-network:
    driver: bridge
