http.host: 0.0.0.0
xpack.monitoring.elasticsearch.hosts: 192.168.2.100:9200
xpack.monitoring.elasticsearch.password: changeme
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
